#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 25 18:20:09 2022

@author: onurserce
"""

import numpy as np
import pandas as pd

PgMatrix_test = pd.read_csv(
    '~/Desktop/PgMatrix_test.csv', header=[1, 2], index_col=0)
PgMatrix_test = PgMatrix_test.sort_index(axis=1)

PgMatrix_imputed = pd.read_csv(
    '~/Desktop/PgMatrix_test_imputed.csv', header=[1, 2], index_col=0)
PgMatrix_imputed = PgMatrix_imputed.sort_index(axis=1)

PgMatrix_imputed_bool = pd.read_csv(
    '~/Desktop/PgMatrix_test_imputed_bool.csv', header=[1, 2], index_col=0)
PgMatrix_imputed_bool = PgMatrix_imputed_bool.sort_index(axis=1)

PgMatrix_unimputed_bool = pd.read_csv(
    '~/Desktop/PgMatrix_test_unimputed_bool.csv', header=[1, 2], index_col=0)
PgMatrix_unimputed_bool = PgMatrix_unimputed_bool.sort_index(axis=1)

from Imputation import ImputeFromReplicates

Imputed, ImputedBool, UnimputedBool = ImputeFromReplicates(PgMatrix_test)

Imputed == PgMatrix_imputed

ImputedBool == PgMatrix_imputed_bool

UnimputedBool == PgMatrix_unimputed_bool
